server:
  port: 8087
  servlet:
    context-path: /training
  tomcat:
    threads:
      max: 200
    uri-encoding: UTF-8
    basedir: /data/logs/training/access_log
    accesslog:
      enabled: true
      pattern: '{"i":"%{X-Forwarded-For}i","a":"%a","A":"%A","t":"%{yyyy-MM-dd HH:mm:ss.SSS}t","m":"%m","U":"%U","s":%s,"b":%b,"D":%D,"I":"%I"}'
      suffix: .log


management:  endpoint:    shutdown:      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown

spring:
  profiles:
    active: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

mybatis:
  mapper-locations: classpath:/mapper/*.xml  configuration:
    map-underscore-to-camel-case: true

# 建立 DataSource 設置 prefix 前綴 springboot.datasource.oracle (自訂)
# 最後一層設置 jdbc-url、username、password、driverClassName、maximumPoolSize、connectionTimeout (預設)
springboot:
  datasource:
    oracle:
      jdbc-url: jdbc:oracle:thin:@localhost:1521:xe
      username: LOCAL
      password: root
      driverClassName: oracle.jdbc.driver.OracleDriver
      maximumPoolSize: 2
      connectionTimeout: 30000
    mysql:
      jdbc-url: jdbc:mysql://localhost:3306/local_db
      username: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver
      maximumPoolSize: 2
      connectionTimeout: 30000
